### PR TITLE
Bundle GROUPS extension

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by allemangD** [comment]
Generally I'm okay with this... the only concern is that SPHARM-PDM also has some dependency on GROUPS now, since we've moved the changes from SlicerSALT upstream. 

https://github.com/NIRALUser/SPHARM-PDM/commit/793975874d8deb5eb6879b56c7f3feb5f51d77cd

So should this kind of change be made to SPHARM-PDM instead, or to bundle GROUPS with SPHARM-PDM to reflect that dependency?

**Comment by bpaniagua** [comment]
Lucia wanted SPHARM-PDM included in SlicerCMF and we thought about updating SPHARM to the latest version (that includes GROUPS)

**Comment by jcfr** [comment]
> the only concern is that SPHARM-PDM also has some dependency on GROUPS now,
> [...]
>  about updating SPHARM to the latest version (that includes GROUPS)

It looks like GROUPS is currently a "soft" dependency of SPHARM. Indeed, GROUPS is built by SlicerSALT (see [here](https://github.com/Kitware/SlicerSALT/blob/345f48977013b4cfa8a3c3f9240cb27bfb0ea77a/CMakeLists.txt#L211-L224)).

This means that applying these changes to `SPHARM-PDM` is a sensible path forward, it will allow to simplify SlicerSALT and also ensure SlicerCMF includes the functionality without having to create a dedicated GROUPS extension.

**Comment by bpaniagua** [comment]
> > the only concern is that SPHARM-PDM also has some dependency on GROUPS now,
> > [...]
> > about updating SPHARM to the latest version (that includes GROUPS)
> 
> It looks like GROUPS is currently a "soft" dependency of SPHARM. Indeed, GROUPS is built by SlicerSALT (see [here](https://github.com/Kitware/SlicerSALT/blob/345f48977013b4cfa8a3c3f9240cb27bfb0ea77a/CMakeLists.txt#L211-L224)).
> 
> This means that applying these changes to `SPHARM-PDM` is a sensible path forward, it will allow to simplify SlicerSALT and also ensure SlicerCMF includes the functionality without having to create a dedicated GROUPS extension.

Lets do it 😎

**Comment by jcfr** [comment]
> > applying these changes to SPHARM-PDM is a sensible path forward

> Lets do it 

Since there are GROUPS changes specific to SlicerSALT (See https://github.com/slicersalt/GROUPS/commits/slicersalt-2021-05-26-b2bd6008), the support for these will be done by adding build options ...

**Comment by jcfr** [comment]
Update of GROUPS and RigidAlignment to support SlicerSALT naming convention and build requirements:
* Commit https://github.com/slicersalt/GROUPS/commit/d3cdb2427f47b32cc1c334e9ee437e1d3b24cb17 (`[slicersalt] ENH: Disable building of non-used extensions`) superseded by https://github.com/NIRALUser/GROUPS/pull/29
* Commit  https://github.com/slicersalt/GROUPS/commit/95fd339a0fe90dacc478a6c879728270b94ba84b (`[slicersalt] ENH: Rename Rigid Alignment extension`)  superseded by https://github.com/NIRALUser/GROUPS/pull/30
* Commits https://github.com/slicersalt/RigidAlignment/commit/a12001cfa1b2f1ab6ddcdc0057dcb6178d97db58 and https://github.com/slicersalt/GROUPS/commit/bdd9129fee6dcff237347ce2f1a55d91e13bb537 superseded by https://github.com/NIRALUser/RigidAlignment/pull/6

**Comment by jcfr** [comment]
Once the PR references above have been integrated in their respective repo, I will submit a PR updating `SPHARM-PDM`

@bpaniagua  @allemangD  could you help with the integration ?

**Comment by bpaniagua** [comment]
> could you help with the integration ?

reviewing?

**Comment by jcfr** [comment]
> reviewing?

Reviewing/integrating/updating SlicerSALT to set the relevant options allowing the customization.

**Comment by bpaniagua** [comment]
Just confirming, you need reviews on these 4 commits

**Comment by jcfr** [comment]
(1) These three pull requests need to be reviewed in the context of SlicerSALT and then integrated:
* NIRALUser/GROUPS#29
* NIRALUser/GROUPS#30
* NIRALUser/RigidAlignment#6

(2) SlicerSALT will then need to be updated to leverage the changes integrated in these pull requests.


> Just confirming, you need reviews on these 4 commits

In the meantime, I am closing this PR.

**Pull request closed without merging**
