### PR TITLE
ENH: Add ShapeVariationAnalyzer dependency

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by bianchijonas1** [comment]
ShapeVariationAnalyzer is still not working; available in the CMF extension 
(windows 10 v 1903. Slicer nightly  4.11.0-2020-07-18 r29221 / 26fbefd )

**Comment by jcfr** [comment]
Thanks for the report

> ShapeVariationAnalyzer is still not working; available in the CMF extension

Based on the dashboard, the extension is expected to be available for download. See https://github.com/DCBIA-OrthoLab/SlicerCMF#dependencies

Could you create (or updated) the relevant issue at https://github.com/DCBIA-OrthoLab/ShapeVariationAnalyzer/issues ?

**Comment by bianchijonas1** [comment]
> Thanks for the report
> 
> > ShapeVariationAnalyzer is still not working; available in the CMF extension
> 
> Based on the dashboard, the extension is expected to be available for download. See https://github.com/DCBIA-OrthoLab/SlicerCMF#dependencies
> 
> Could you create (or updated) the relevant issue at https://github.com/DCBIA-OrthoLab/ShapeVariationAnalyzer/issues ?

Yes, I will check and do this.
thank you
Jonas

**Comment by jcfr** [comment]
> Yes, I will check and do this.

It turns out this is already captured by https://github.com/DCBIA-OrthoLab/ShapeVariationAnalyzer/issues/48

We will address the issue and let you know when to try again.

**Pull request merged**
